### PR TITLE
Mtl cleanup

### PR DESCRIPTION
**Pull request by moltob**
Tried to do a bit more template cleanup to make the generated code free of errors and most of the warnings:

* Fixed import statements, also removed the duplicate import of `ecore.*`and `as Ecore`.
* Removed the unneeded (or did I miss anything) implementation of `__init()`, added a `pass` if the class has no features at all.

### CODE REVIEW

**Comment by aranega** [comment]
Wow, that's so great!

I've check the PR and it seems fine to me. I just need to re-generate some metamodels to see if everything's good. I remember that in an old PyEcore version, the `__init__()` call was mandatory, because of the poor metaclass management I had introduced (but I think I fixed that, I can't remember).
Anyway, if the generated code works for you, it's almost 99% sure that all is fine. I'll check this today! 

Once again, thanks a lot Mike!

**Comment by moltob** [comment]
Let me know how the generated code looks to you. Just wanted the output to be usable and debuggable. I'll probably switch to using the dynamic version soon. In theory we could generate static classes also via metamodel instance reflection in Python, without going trough Acceleo at all, but use jinja etc. Would probably be even more appealing to Python devs. Maybe I'll tackle that at some point.

**Comment by aranega** [comment]
You're right, a mode usable and debuggable code is better and your modifications are very welcome. 

The generated code looks very good to me, but I know I've probably done some nasty stuffs in the core of PyEcore (I'm no Python expert at all). 

I've finish testing your, everything's almost perfect, there is just a thing on one of the import management [L9](https://github.com/moltob/pyecore/blob/e3aea24c09bda2ec5d09d8da59a0cd4132638bc0/generator/ecore2pyecore.mtl#L9), actually, the `eClassifier` dict is added dynamically to the module namespace by `pyecore.py` when each `EClassifier` is registered and `getEClassifier` is also dynamically added at the same moment as a new partial function (told you about nasty stuffs). So the call should still stay

    from .[p.name/] import eClassifiers, getEClassifier

instead of just:

    from pyecore.ecore import eClassifiers

I know that in Python, explicit is better than implicit, but the "glue" was a little bit "complex" to generate and introduced too much noise in the generated code. I should perhaps change that in future versions by finding a more elegant way of doing this.

The static version is great if you have a lot of derived attribute and `EOperation` behavior to add. If not, the dynamic version should do the trick. As I tried to unify a lot the way PyEcore works for the dynamic and the static mode, there is not so much performances differences between the two modes.

And you're totally right about reflection/generation. It would be better to have a full Python generator from an `.ecore` file. I've this in mind for a while and I tried to check existing tools to do this, but I wasn't sure which one should be used. I checked `cog` but I'm not a big fan, and very quickly `jinja`, but I wasn't sure that we are able to generate full file hierarchies using it (I also checked some from [this list](https://wiki.python.org/moin/Templating)) . The first version in Acceleo was more an "obligation" at the time, as I hadn't any way of handling `EObject` in Python and PyEcore was not stable enough to properly manage `.ecore` files.

**Comment by moltob** [comment]
OK, thanks for the feedback. I'll quickly "verify" what you explained and then readd  the import. Just to understand better the internal dynamics.

**Comment by aranega** [comment]
So, I checked a little bit, and I think a good way of improving the generated code readability would be to explicitaly use:

In the module code, this would be added
```python
from functools import partial  # for the getEClassifier definition from the one in the Ecore metamodel
import pyecore.ecore as Ecore  # in order to have a reference to the Ecore metamodel in itself

# other stuffs

eClassifiers = {}
getEClassifier = partial(Ecore.getEClassifier, searchspace=eClassifiers)

# rest of the code
```
As a result, the `__init__.py` code will stay:

```python
from .mylib import getEClassifier, eClassifiers
```
But will be more understandable. This still works on the dynamically population of the `eClassifiers` dict but will be better because less implicit.

If you agree with this, I could merge your PR and make the aforementioned modifications.

**Comment by moltob** [comment]
Yes, this is much less hidden. Thanks a lot.

**Pull request merged**
