### PR TITLE
Python generator

### PR DESCRIPTION
**Pull request by moltob**
Hi Vincent,

this is the first PR (or the first part of it) for the Python generator. I'd appreciate your feedback. Before you merge it (or merge it to master) I'd like to:

* Write more tests for all the generator features realized in the templates. Currently I copied your tests or the MTL generated library example, and these are green. But I want to get complete feature coverage via tests.
* Refactor the pygen base classes into a standalone project. The approach is generic and independent of Jinja as well as Pyecore.

I wrote documentation of how the generator is used and about the design in `pyecore/pygen/pygen.rst`.

You find all the code in the top-level pygen folder. The generator uses pep8 autoformatting to clean up the generated code afterwards.

Let me know what you think. I am looking forward to any comments or feedback you have.

Best,
Mike

### CODE REVIEW

**Comment by moltob** [comment]
I've seen the Python 3.3 and 3.4 builds are failing. I'll look at this ASAP, unless you want to drop support there... :-)


Anyway, I think you can still already look at the API and the general design and let me know what you think.

TTYS,
Mike

**Comment by aranega** [comment]
Hi Mike,

Wow, that's awsome! I'm looking to this as soon as I can (probably tomorrow morning), again, thank you so much for doing this! 

* Regarding the Python compatibility, I would prefer to keep the Python 3.3 and 3.4 support, I saw that there is some backports for type hinting, but I really don't know the impact it produces on the code. I can check that if you want.
* About the production as an independent project, I think this is a great idea, I was wondering if it could be interesting to create a github "organization" for PyEcore and PyEcore related projects as pygen, what do you think?
* Tell me if you need help for tests, I can write some and/or write a generator for them.

Thank you so much for your work!
Vince

**Comment by moltob** [comment]
**Python 3.3/3.4**

I already removed dependencies on the `typing` module last night, but it still does not work. Looks like there are issues with the way I am using mocks and the pytest fixtures. The current issues seem to result from incompatibilities with `unittest.mock` in those older versions. I'll install 3.3 on my machine tonight and track the bugger down.

**Pyecore organization**

That does make sense. However, since the core of the small framework is also independent of Pyecore itself, I think I would create a completely separate project for it. Within the organization, we can then have a generator project, that uses pygen and also adds for instance command line support, so you can:

```
$ pygen some/model.ecore output/path
```

What do you think? So in the end we'd have 3 projects: pyecore, pygen (my independent generator) and "pyecoregen", the first and the last being part of the project organization.

**Tests**

If you don't mind I'd like to write those tests myself. It'll help me to understand Pyecore yet a bit better and spares me the embarrassment of stupid bugs in currently untested code. :-)

**Comment by moltob** [comment]
Small update: installed Python 3.3 and it throws the same issue as the 3.4 test on Travis (mocking open). I guess the many issues in 3.3 are then somehow related to running under Linux. As those tests all deal with file generation it's maybe a path or slash issue. Stay tuned.

**Comment by aranega** [comment]
I've started to look to the sources and, wow, you've done a tremendous work here, this is awesome! Sorry, I need a little time to process everything as I really don't know Jinja at all and as there is many concepts I still need to connect ;).

The look I gave is so much promising, everything looks modular. I currently concentrate the reading on the `ecore.py` and the `*.py.tlp` files. Of course, I have some questions :)

I saw that the `filename_for_element` gives the name of the file that will be generated. 

```python
@staticmethod
 def filename_for_element(package: EPackage):
    return '{}.py'.format(package.name)
```

Is this possible to generate a directory hierarchie from this method? E.g:

```python
@staticmethod
def filename_for_element(package : EPackage):
    return '{}/{}.py'.format(package.name, package.name + 'File')
```

Also, do you think it could be possible to use a kind of `Task` decorator to set the template file name and the element type? In order to have something like this:

```python
@pygen.Task(template_name='package.py.tpl', element_type=EPackage)
class EcorePackageInitTask(EcoreTask):
    # ... following code
```

and perhaps also a way of registering the different filter/tests, also by decorator (disclamer, I love decorators)? In some case, the name of the filter/test could be infered by reflexion (I suppose):

```python
@staticmethod
@filter('all_contents')
def filter_all_contents(value: EPackage, type_):
    """Returns `eAllContents(type_)`."""
    return [c for c in value.eAllContents() if isinstance(c, type_)]
```

The idea is to simplify some artifacts registration, but while letting the ability to register them as in the current version. 

By the way, some of your filter could be very interesting for other generators (e.g, I'm pretty sure that the `all_contents` would be very useful), it could be great to provide a basic library with some 'generic' filter/tests that could be close some that can be found in OCL (for example), what do you think?

So, currently, if I understand correctly, 2 independent projects will be born from your work:

1. the PyGen framework, for multi-files code generation using either Jinja or any other template engine, from any kind of input,
2. PyEcoreGen, which embedded a dedicated layer that bridges PyGen and PyEcore and provides the ecore -> python generator

Did I understood this right?

Regarding the Python 3.3/3.4 compatiblity, I saw in the tests that the parameter `scope` is missing from the fixture in `test_ecore.py` and `test_generated_library.py`, for `cwd_module_dir`. Could this be an issue?

Mike, thank you, again, so much for your work! With the command line facilities, I think it could really motivate people to use/develop MDE based code generators.

**Comment by moltob** [comment]
First a question up front: Did you get a chance to look at the [documentation file](https://github.com/moltob/pyecore/blob/pygen/pygen/pygen.rst)? I tried to explain some of the top-level concepts there.

Now back to your questions:

# `filename_for_element` being able to produce hierarchies

No and it's not supposed to. :-) As the name says it's a filename, not a path. But: The generic pygen framework actually wants to have the abstract method `relative_path_for_element` get implemented, and this is including arbitrary sub folders. In our case, where we generate an `EPackage` into a separate folder, I provided a base implementation in `EcoreTask` which delegates to `folder_path_for_package`, implemented right there, and the method you looked at, implemented in the more specific derived classes.

So I think we are good.

# Use of decorators

I sure noticed you like them. However, in this case I tend to disagree. I like to see decorators if they add some orthogonal or independent or otherwise hard-to-add attribute. However, in this case, the task and generator classes have only one purpose, namely to implement one specific generation pattern. E.g. template path and names are inherent properties of this purpose. Even though it has a biot of coolness factor I don't see a real good reason for moving class attributes to decorators.

As a side note: This kind of design, utilizing base classes, that define class attributes, which are then overridden in the specific-purpose-classes is more or less taken directly from the Django [class-based views](https://docs.djangoproject.com/en/1.11/topics/class-based-views/) pattern. Django is usually considered well-designed, and I kind of like it.

Unless you really oppose the current way I'd like to stick to it and not replace it with decorators.

# OCL library

Sure, but let's get this one out of the door first. :-) But I agree that they can be useful.

# Library split

Yes, you're right. PyEcoreGen would be part of your organization, PyGen my separate project. I suggest we make this work first within the Pyecore repository and refactor afterwards. The API within PyEcore will not change much (except for the package name maybe).

# UT breaker

Thanks for the hint. In recent Python versions that argument is optional, but I'll look at it ASAP. Stay tuned for the build turning green...

Thanks for welcoming the work, this is a lot of fun!

**Comment by aranega** [comment]
Indeed, I read the documentation, but I think I was a little bit confused by all the possible combinations that could be used by the choice of the different `Generators` classes. I think I'm beginning to connect all the dots.

# `filename_for_element` being able to produce hierarchies

Ok, got it!

# Use of decorators

No problems with the 'non-use' of decorators. The idea was not to replace the current way, but to let you the ability to use decorator if you want.  I like them because of the finer semantic they add to class/methods (like `@staticmethod` or `@classmethod`) and also because (to my mind) they ease de learning curve, but if you don't find that they have their place here, I hear your point and I respect that :)

# OCL library & Library split

Of course, I totally agree with you, first things first, everything can be in PyEcore at the moment and, once everything is working, spliting into different projects.

I think I will try very soon to define a quick'n dirty SQL metamodel and write a SQL generator to see if I'm able to tame pygen and jinja.

Thanks again Mike!

**Comment by moltob** [comment]
Tests just turned green. The Python 3.3 issue was weird. The Ninja Template Loader that loads from packages does not seem to work under Python 3.3 on Linux. It did just fine on Windows. I switched to the `FileSystemLoader` and did the package path computation myself.

So now I'll start doing the tests to get everything from the template. I suggest we keep the PR open, so my pushed commits are directly evaluated by Travis, so we keep a green build. I let you know once I am done the PR is ready to get merged.

**Comment by aranega** [comment]
I don't know how you found this, but that's great! Thanks a lot to have dealt with this issue and sorry to bother you with old Python compatibility. By experience, I know that many people stick with their distribution version of Python (Debian jessie is still on Python 3.4 for example) and as I'm certain PyEcore is not used a lot at the moment, restraining the Python version it can run with could add a 'cost' for people that wanting to quicly try it.

I let the PR open as you suggested, and I continue to look/experiment with pygen :-)

**Comment by moltob** [comment]
Hey Vince, just noticed yesterday that sth is fishy hob hierarchical packages are treated. Didn't get to it yesterday, today is tight, too. I'll look into it ASAP. Just letting you know so you're not surprised when using it. This is prealpha until we have full coverage... :-)

**Comment by moltob** [comment]
I have fixed a few things, but there is one question that I have. In The MTL file in line 15, you have this expression:

```
sub.qualifiedName().replaceAll('^[^.]+', '')
```

If I read this correctly you are saying to cut away any leading periods. Why and in which situation would I have those? I am generating a Python path, and there would never be a dot...

Thanks,
Mike

**Comment by aranega** [comment]
That's great news Mike! 

Regarding the expression, it does not remove the leading periods, but it removes the first word in a qualified name so it becomes a relative path:

    xxx.yyy.zzz --[becomes]--> .yyy.zzz

The `[^.]` stands for 'everything that is not a `.`'. 

In the same time, I'm playing with pygen (which allowed me to fixed an issue on `develop` regarding dynamic metamodels by the same occasion) and I really like the way it goes. Currently, I only feel it misses a small generic layer between pygen and pyecore to build an awesome M2T framework. I'm really enjoying it :-), thanks Mike!

**Comment by moltob** [comment]
Of course, negated character group... I do know it, actually. Sorry for the miss.

**Comment by moltob** [comment]
Hey Vince,

I think I got pretty good coverage of the template code. I think you can go ahead and after giving the code another review merge it to develop. Please note that I did change small number of existing files as well, you should review those in particular. Please also note that I did not adapt the part of the README that list the package dependencies, even though I added two new ones (jinja2 and autopep8). I left it out because I am not too convinced it is a good idea to copy them from ``setup.py``. This will run out of sync as the project grows. But of course, I'll add it if you like. Just let me know.

After we get this merge done, I will add the command line script and refactor out the two separate projects. For this I would appreciate if you could at some point create the pyecore organization and create an empty pyecoregen project inside. I would then refactor the ecore specifics into that project and create my own for pygen.

Best,
Mike

**Comment by moltob** [comment]
One last comment: the only difference in the generated code to the MTL version (that I am aware of) is that for non-required operation arguments pygen creates a ``=None`` clause, which is not yet part of the MTL. But that should be it.

**Comment by aranega** [comment]
Hi Mike,

That's so great! I look to all of this first thing tomorrow in the morning. I think I will create the organization and the empty repository in the same time. I quickly checked the modifications you performed on the existing files, they seems perfectly fine to me.
Really, thank you for improving the project!

Regarding the README, indeed, it is perhaps not a good thing to directly list the extra dependencies as they will move with the project when the refactoring/split of pygen/pyecoregen will be done. Don't worry at the moment for the README, when everything will ready for a merge towards master, we will check again what's missing.

Also, good call on the non-required parameters, I will update the MTL generator as well. This property is checked for dynamic metamodel, but I totally forgot to handle it for the static metamodel generator.

The next PyEcore release will be impressive.

Once again, thank you so much Mike for all your work and your help on this project!

Vince

**Comment by aranega** [comment]
Hey Mike,

I took a look to your code/commits, everything's perfect to me so I merged everything in develop. The only "missing" thing I saw is the XML to Ecore type translation for `EAttributes` that could be easily added line 158 from the `pygen/ecore.py` file, using a translation dict (if I understood correctly, tell me if I'm wrong).

I'm going to create the organization in the same time, transfert the main PyEcore repository and create the PyEcoreGen one. Will you release soon pygen to Pypi?

Thanks again so much for your tremendous work!

**Pull request merged**
